- from scipy.stats import chi2_contingency

- scipy.stats.chisquare

In [ ]:
import numpy as np

### Contingency table
tab = np.array([[6,20],[13,5]])

### SciPy
from scipy.stats import chi2_contingency

chi_val, p_val, dof, exp_val = chi2_contingency(tab)

print("Chi square test\nChi squared = %f\np           = %f\nDOF         = %d"%(chi_val, p_val, dof))

Chi square test
Chi squared = 8.563275
p           = 0.003430
DOF         = 1


In [ ]:
import numpy as np
from scipy.stats import chi2_contingency


table = np.array([[90, 60, 104, 95],
                  [30, 50,  51, 20],
                  [30, 40,  45, 35]])

chi2, p, dof, expected = chi2_contingency(table)

print(f"chi2 statistic:     {chi2:.5g}")
print(f"p-value:            {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)

chi2 statistic:     24.571
p-value:            0.00040984
degrees of freedom: 6
expected frequencies:
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


-----------

In [ ]:
from scipy.stats import chisquare
chisquare([16, 18, 16, 14, 12, 12])

Power_divergenceResult(statistic=2.0, pvalue=0.8491450360846096)