In [1]:
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

### Logistic Regression

In [12]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target, cv=3)
l_scores

C:\Users\deepusuresh\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0.98, 0.96, 0.98])

In [13]:
np.average(l_scores)

0.9733333333333333

### Decision Tree

In [14]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)
d_scores

array([0.98, 0.92, 1.  ])

In [15]:
np.average(d_scores)

0.9666666666666667

### Support Vector Machine (SVM)

In [16]:
s_scores = cross_val_score(SVC(), iris.data, iris.target, cv=3)
s_scores

array([0.96, 0.98, 0.94])

In [17]:
np.average(s_scores)

0.96

### Random Forest

In [18]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv=3)
r_scores

array([0.98, 0.94, 0.94])

In [19]:
np.average(r_scores)

0.9533333333333333

**Best score so far is from SVM: 0.97344771241830064**